### ISSUE TITLE
Backfill thumbnails on demand

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#126]
Thumbnails are created for an asset on ingest.
Later the thumbnail policy might be updated. A large number of images might acquire a new thumbnail policy. This is a reference to a policy in the thumbnails table, not an atomic policy-per-image (although it's possible that a policy could be in use on 1 or 0 images).

What should happen immediately when the policy changes, and what can be deferred until a thumbnail is requested?

The active thumb policy is part of the cached redis object in Orchestrator.
How does Orchestrator know that the thumbs in S3 are still the ones described by this policy?

If a thumbnail size is asked for that it in the policy but is not on S3, we create it there and then and update the S3 thumbs (re-apply the whole policy not just the one asked for and delete any thumbs no longer specified in the policy).

**Comment by donaldgray** [comment]
When this is implemented, update the `OrchestrationAsset` to generate thumbnail sizes from DB policy rather than reading `s.json`

**Comment by tomcrane** [comment]
After discussion on 19/09/2023 we decided we should not backfill on demand. If you change a policy and want thumbs reingested, you should reingest the image.

**Comment by tomcrane** [comment]
(closing, #wontfix)
