### ISSUE TITLE
Direct POST of binary content to API

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#16]
The API should support an operation that allows you to submit a local file from disk straight to the DLCS - that is, no intermediate origin required on the part of the end user of the API.

This can then be wrapped up in Python client libs for simple ingest scenarios, and included in https://github.com/dlcs/dlcs-cli. A Python client lib would then allow you to do

`dlcs.register_image('~/images/my_image.tiff', ... args)`

.. or create a batch from a folder / glob, etc.

The DLCS would still make an origin for the image, but the user doesn't have to care about it.

**Comment by tomcrane** [comment]
Scenarios: 

 * API endpoint is the ACTION of an HTML form - multipart-form-upload ?
 * API endpoint accepts PUT of a binary payload direct to DLCS image resource (an image id in a space in a customer)
 *  - (optionally) with a JSON wrapper?
 * API endpoint accepts a POST of binary content to an image-ingestor

Things to consider - how does the image record get the other bits of metadata it needs?

Use cases need fleshing out.

**Comment by mattmcgrattan** [comment]
SOAS Use Case:

* API endpoint accepts a METS/MODS XML file
* Service parses the METS fileptrs to identify the location of the binary image files:
    * If it's an HTTP(s) endpoint, potentially register the image directly with DLCS (in the 'traditional' manner)
    * if a filesystem location, use the binary payload API (as above) to PUT/POST the image directly to the DLCS
* Service receives back from DLCS the info.json and uses this to update the IIIF Presentation API manifest that has been created from the METS

In this case, we have metadata for the image (label, position in a sequence, etc) that can be used to generate data for a named query by using the structMap in the METS.

**Comment by tomcrane** [comment]
As suggested in #24, we would like to use this requirement to make a start on the new API service.

However, it is a more immediate requirement for several clients, and the cost of implementing this in a new API app might be too high.

The alternative approach is to introduce a new sidecar app that accepts the POST/PUT image and creates an S3 origin for it, but then calls the existing API to ingest it and ensure that the behaviour stays the same.

This sidecar would be:

New project + ECS service, with 1 Action Method that:
 - accepts data (in 1 specified format, whichever works for Delft/SOAS)
 - calls GET customer/ to verify supplied auth credentials
 - uploads bytes to S3
 - PUTs to DLCS
 - return DLCS result

This is simpler but ends up with more moving parts overall, and pays down no technical debt.

We have suggested some mini DLCS product sprints. This feature seems like an excellent candidate for a week-long sprint, to deliver additional value and work towards the new API application.

As a new API application rather than just a sidecar, we wouldn't call the old API at all. We'd have to make sure that our image PUT behaviour was identical: e.g., produce equivalent end states for `CreateSkeletonImageLocationBehaviour`, `SelectImageOptimisationPolicyForImageBehaviour` - are these needed, do they have side-effects etc.

But we could timebox an approach that sees it starting as a sidecar, but if goes well ends up as the minimal API2 service:

1. sidecar approach as above
2. still got time? bring the 'auth' check into api2 (removing GET /customer/{x}).
3. still got time? bring the PUT logic into api2

If we need to stop at any point we have something api2-ish deployed, and can return to it later.

Estimates:

* 1-2 days for the sidecar approach, or
* 1 week for the timebox / product sprint that adds an API service to the protagonist .[NET solution](https://github.com/dlcs/protagonist/blob/master/protagonist.sln)

The first 1-2 days of these are identical.

**Comment by donaldgray** [comment]
>API endpoint accepts a POST of binary content to an image-ingestor

This is covered by https://github.com/dlcs/protagonist/pull/55

**Comment by donaldgray** [comment]
Closing as this has been implemented in API
