### ISSUE TITLE
Orchestrator should support path aliases

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#19]
This comes from https://github.com/wellcomecollection/platform/issues/4603#issuecomment-662407221

The DLCS orchestrator should be updated to handle aliases for the `operation/customer/space` path segment triplet, where the alias can be a combination of host name and path segment.

hostname: iiif.wellcomecollection.org, path segment image: => iiif-img/wellcome/5
hostname: iiif-stage.wellcomecollection.org, path segment image: => iiif-img/wellcome/6

This better supports custom URL schemes, and DLCS users like Wellcome who are not sharing a DLCS service and don't need `customer` and `space` reflected in the URLs.

It's still useful to allow space, for partitioning, but support a default space that can be assumed.

**Comment by tomcrane** [comment]
The Wellcome AWS Application Load Balancer has rules like:

image/L00* => loris
image/s3:* => loris
image/* => dlcs

at the moment the behaviour in the initial comment means
https://iiif.wellcomecollection.org/image/L0056318 => https://dlcs.io/iiif-img/2/5/L0056318

...but L0056318 is in space 8, at https://dlcs.io/iiif-img/2/8/L0056318.

If currently Loris paths stay the same:

https://iiif.wellcomecollection.org/image/b28047345_0006.jp2 => https://dlcs.io/iiif-img/wellcome/5/b28047345_0006.jp2
but
https://iiif.wellcomecollection.org/image/L0056318 => https://dlcs.io/iiif-img/wellcome/8/L0056318

In the ALB rules above, if we switched the rule image/L00* => loris to dlcs, it would arrive at space 5.

This orhestrator enhancement needs to look at more than the first path segment.
Instead it needs to pattern match on the whole path, and accommodate basically the same rules internal to the DLCS for deciding between space 8 and space 5, as the ALB uses to decide between loris and dlcs.

**Comment by tomcrane** [comment]
If this is implemented in current Orchestrator, we would VERY much prefer to confine all this logic to NGINX config. No additional C# code in Orchestrator.

**Comment by tomcrane** [comment]
Update:

The need to handle aliases directly on Wellcome has gone (although a good feature for later).
However DLCS still needs to handle paths that have been rewritten before they arrive (e.g., at Cloudfront):

https://github.com/wellcomecollection/platform/issues/4997#issuecomment-770741264

This means the DLCS needs to me able to rewrite URLs on the way out - the `@id` property of info.json.
But _only_ if the incoming request was on the rewritten host and path.
So it needs to inspect forwarded-for header, and also needs access to the original path (presumably Cloudfront provides this).

**Comment by tomcrane** [comment]
What are the implications of this for auth services? (if any)

**Comment by donaldgray** [comment]
> What are the implications of this for auth services? (if any)

Orchestrator needs to set auth cookie for appropriate domain (e.g. CloudFront domain and dlcs origin domain).

> So it needs to inspect forwarded-for header, and also needs access to the original path (presumably Cloudfront provides this).

Out of the box CloudFront doesn't add `X-Forwarded-For`, it has to be added as a `custom_header` to the origin but this is straightforward (see https://github.com/wellcomecollection/platform-infrastructure/pull/122).

> also needs access to the original path

Path is rewritten at CloudFront using a predictable conversion. This is reflected in DLCS via the `"PathRules"` setting (see below).

> This means the DLCS needs to me able to rewrite URLs on the way out - the @id property of info.json.

Both Thumbs and Orchestrator have this. These services handle `"PathRules"` appSetting where the following slugs can be used to generate Ids:

* `{prefix}`
* `{assetPath}` 
* `{space}`
* `{customer}`

e.g. 

```
"PathRules": {
  "Default": "/{prefix}/{customer}/{space}/{assetPath}",
  "Overrides": {
    "my-proxy.com": "/{prefix}/{assetPath}"
    }
}
```
