### ISSUE TITLE
Image Server Cluster

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#22]
implement a cluster of 1..n image servers
Load balancing across this cluster is provided by Orchestrator, via YARP

 - use Cantaloupe, not IIPImage
 - investigate AWS [multi-attach](https://aws.amazon.com/about-aws/whats-new/2020/02/ebs-multi-attach-available-provisioned-iops-ssd-volumes/)
 - while other services might be containers, the image server cluster might be straight EC2s

**Comment by donaldgray** [comment]
Superseded by #241
