### ISSUE TITLE
New Orchestrator

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#23]
Orchestrator is now **_itself_** the load balancer and reverse proxy, rather than using NGINX in front of .NET.

 - includes Redis to track asset state and location
 - enforces access control on assets
 - Optionally uses disk-based web cache ([but see this](https://github.com/microsoft/reverse-proxy/issues/120)) or Cloudfront

**Comment by tomcrane** [comment]
Possibly #12 

This needs revisiting

**Comment by donaldgray** [comment]
Closing this as we have the basics for a YARP-based Orchestrator implementation. Tickets can be tracked on [Orchestrator board](https://github.com/dlcs/protagonist/projects/3) or https://github.com/dlcs/protagonist/labels/orchestrator.

Regarding the 3 points raised in the initial comment:
* Includes Redis to track asset state and location - see #272 
* Enforces access control on assets - this is done, see https://github.com/dlcs/protagonist/labels/auth tickets
* Optionally uses disk-based web cache (https://github.com/microsoft/reverse-proxy/issues/120) or Cloudfront - CloudFront, or alternative CDN already supported. Need to track linked ticket for disk-based cache.
