### ISSUE TITLE
Purge images/tiles from cache

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#233]
The DLCS stores/caches images at a few different levels. 

A typical setup will include the Orchestrated image on disk, tiles cached in Varnish and possibly an external CDN (e.g. CloudFront).

We need some way to trigger the invalidation of these images, ideally in bulk.

We need some mechanism that can respond to a request to invalidate at all of those levels. Possibly by responding to messages placed into a queue.

Manually clearing the cache would involve
* Delete orchestrated image (`rm -f -r /path/to/orchestrated`). To do this the component would need access to the filesystem where orchestrated images are stored, and would need to use same folder format.
* Delete Varnish via `varnishadm` (e.g. `ban req.url ~ /iiif-img/<customer>/<space>/<image>`). Varnish would need admin enabled (e.g. via `-T` arg) and component would need to be able to call this. With `varnishadm` tool only? The [DLCS Varnish](https://github.com/dlcs/dlcs-varnish/blob/master/start.sh#L11) dockerfile uses port 6082 but this is typically _not_ exposed.
* Invalidate external cache (`aws cloudfront create-invalidation --distribution-id ABC123 --paths "/iiif-img/<customer>/<space>/<image>*"`).

**Comment by tomcrane** [comment]
superseded by #252
