### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#24]
Implement the existing API as defined at https://dlcs-book.readthedocs.io/en/latest/

- Vanilla ASP.NET API Application on .NET Core (5)
- expose more control over things that are opaque JSON config blobs
- Develop alongside new Portal

**Comment by tomcrane** [comment]
Regarding issue #16 
This is a current requirement for Delft which we could meet on old Deliverator with a temporary sidecar application.

Rather than doing it that way, we could use this as a chance to make a start on API v2.

We can have a new API webapp that runs alongside the old one, but doesn't handle very much yet. We then have something we can come back and add to later.

We add whatever API ops are needed to support the Delft functionality, including an endpoint that can be used as the action of an HTML form. There are probably a few POST and PUT variants this could support, and a few variant ways of accepting API credentials, including as form request params.

Current API uses HTTP Basic Auth over HTTPS, but could use more ways of maintaining session for different usage.

**Comment by stephenwf** [comment]
Some thoughts on possible JWT option here: https://github.com/digirati-co-uk/dlcs-api-specification/pull/2

**Comment by tomcrane** [comment]
Need to revisit this PR and come up with a strategy for applying it to the rest of the Portal and API:

https://github.com/dlcs/protagonist/pull/199

**Comment by donaldgray** [comment]
- [x] GET `/customers/{customer}`
- [x] PATCH `/customers/{customer}`
- [x] POST `/customers/{customer}/allImages`
- [ ] GET `/customers/{customer}/authServices/{authService}`
- [ ] PUT `/customers/{customer}/authServices/{authService}`
- [ ] DELETE `/customers/{customer}/authServices/{authService}`
- [ ] GET `/customers/{customer}/authServices/{authService}/roleProvider`
- [ ] PUT `/customers/{customer}/authServices/{authService}/roleProvider`
- [ ] GET `/customers/{customer}/authServices`
- [ ] POST `/customers/{customer}/authServices`
- [x] GET `/customers/{customer}/customHeaders/{customheader}`
- [x] PUT `/customers/{customer}/customHeaders/{customheader}`
- [x] DELETE `/customers/{customer}/customHeaders/{customheader}`
- [x] GET `/customers/{customer}/customHeaders`
- [x] POST `/customers/{customer}/deleteImages`
- [x] GET `/customers/{customer}/keys`
- [x] POST `/customers/{customer}/keys`
- [x] DELETE `/customers/{customer}/keys/{key}`
- [x] GET `/customers/{customer}/namedQueries`
- [x] POST `/customers/{customer}/namedQueries`
- [x] GET `/customers/{customer}/namedQueries/{namedQuery}`
- [x] PUT `/customers/{customer}/namedQueries/{namedQuery}`
- [x] DELETE `/customers/{customer}/namedQueries/{namedQuery}`
- [x] GET `/customers/{customer}/originStrategies`
- [x] POST `/customers/{customer}/originStrategies`
- [x] GET `/customers/{customer}/originStrategies/{originStrategy}`
- [x] PUT `/customers/{customer}/originStrategies/{originStrategy}`
- [x] DELETE `/customers/{customer}/originStrategies/{originStrategy}`
- [ ] PUT `/customers/{customer}/originStrategies/{originStrategy}/credentials`
- [x] GET `/customers/{customer}/portalUsers/{portaluser}`
- [x] PATCH `/customers/{customer}/portalUsers/{portaluser}`
- [x] DELETE `/customers/{customer}/portalUsers/{portaluser}`
- [x] GET `/customers/{customer}/portalUsers`
- [x] POST `/customers/{customer}/portalUsers`
- [x] GET `/customers/{customer}/queue`
- [x] POST `/customers/{customer}/queue`
- [x] GET `/customers/{customer}/queue/active`
- [x] GET `/customers/{customer}/queue/batches/{batch}`
- [x] GET `/customers/{customer}/queue/batches`
- [x] GET `/customers/{customer}/queue/batches/{batch}/images`
- [ ] ~GET `/customers/{customer}/queue/batches/{batch}/test`~ ** Not implementing, modifies DB. Use POST instead
- [x] POST `/customers/{customer}/queue/batches/{batch}/test`
- [ ] ~GET `/customers/{customer}/queue/images`~ ** broken in Deliverator
- [x] GET `/customers/{customer}/queue/priority`
- [x] POST `/customers/{customer}/queue/priority`
- [x] GET `/customers/{customer}/queue/recent`
- [ ] GET `/customers/{customer}/queue/recentErrorsByMetadata/{metadata}`
- [x] DELETE `/customers/{customer}/resources/pdf/{query-name}`
- [ ] DELETE `/customers/{customer}/resources/zip/{query-name}` (*new*)
- [ ] GET `/customers/{customer}/roles/{role}`
- [ ] PUT `/customers/{customer}/roles/{role}`
- [ ] DELETE `/customers/{customer}/roles/{role}`
- [ ] GET `/customers/{customer}/roleProviders`
- [ ] GET `/customers/{customer}/roles`
- [ ] POST `/customers/{customer}/roles`
- [x] GET `/customers`
- [x] POST `/customers`
- [x] GET `/customers/{customer}/spaces/{space}`
- [x] PUT `/customers/{customer}/spaces/{space}` ** Implemented as PATCH
- [x] PATCH `/customers/{customer}/spaces/{space}`
- [x] DELETE `/customers/{customer}/spaces/{space}`
- [x] GET `/customers/{customer}/spaces/{space}/images/{image}`
- [x] PUT `/customers/{customer}/spaces/{space}/images/{image}`
- [x] PATCH `/customers/{customer}/spaces/{space}/images/{image}`
- [x] DELETE `/customers/{customer}/spaces/{space}/images/{image}`
- [x] POST `/customers/{customer}/spaces/{space}/images/{image}`
- [x] GET `/customers/{customer}/spaces/{space}/images/{image}/metadata`
- [x] POST `/customers/{customer}/spaces/{space}/images/{image}/reingest`
- [x] GET `/customers/{customer}/spaces/{space}/images`
- [x] PATCH `/customers/{customer}/spaces/{space}/images`
- [x] GET `/customers/{customer}/spaces/{space}/images/{image}/storage`
- [ ] GET `/customers/{customer}/spaces/{space}/metadata`
- [ ] GET `/customers/{customer}/spaces/{space}/metadata/distinct`
- [x] GET `/customers/{customer}/spaces`
- [x] POST `/customers/{customer}/spaces`
- [x] GET `/customers/{customer}/spaces/{space}/storage`
- [x] GET `/customers/{customer}/storage`
- [x] GET `/imageOptimisationPolicies`
- [x] GET `/imageOptimisationPolicies/{imageOptimisationPolicy}`
- [x] GET `/originStrategies`
- [x] GET `/originStrategies/{originStrategy}`
- [x] GET `/queue`
- [x] GET `/storagePolicies`
- [x] GET `/storagePolicies/{storagePolicy}`
- [x] GET `/thumbnailPolicies`
- [x] GET `/thumbnailPolicies/{thumbnailPolicy}`

**Comment by donaldgray** [comment]
Revisit maintenance of CustomerStorage records. Deliverator creates these on the fly when they are read - do we want to follow this process, or create them when Space and Customer are created?

**Comment by donaldgray** [comment]
`POST /customers/{customer}/originStrategies` should have validation to restrict "optimised" to s3-ambient only. see https://github.com/dlcs/protagonist/blob/13c2878deff64bd780f3ef231d9d442e80c51226/docs/adr/0005-optimised-origin.md#optimised-storage

**Comment by donaldgray** [comment]
`storage` and `metadata` properties should be added to API Hydra model population once implemented.

**Comment by donaldgray** [comment]
We should revisit and tidy/consolidate implementation of `CreateCustomer`. I think this was the first "feeling out the structure" implementation of an API request so there's a lot of comments to that effect.

**Comment by tomcrane** [comment]
Will split this issue into different functional areas
