### ISSUE TITLE
Handle Deletions

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#251]
Update API to cleanly handle items deleted from DLCS. 

A deletion action can clean up some resources that the API knows about (ie DB rows) and then raise a notification that can be listened to.

The listener for this service can either be a single deletion service, or respective service can each listen for notifications. We'll need to remove:

* Cached assets
* Orchestrated source assets
* Generated derivatives (info.json, thumbnails)
* Generated NQ results that contain asset?

**Comment by donaldgray** [comment]
https://github.com/dlcs/protagonist/pull/438 contains DeleteHandler app. This is for Deliverator so will need exanded, namely to handle deleting info.json and `T` / `F` assets

**Comment by donaldgray** [comment]
The DeleteHandler project for Deliverator runs as an dockerized service for ease. We should consider running this as a lambda in AWS - either via container or as a script as it will be seldom used.

**Comment by donaldgray** [comment]
The [storage-keys](https://github.com/dlcs/protagonist/blob/main/docs/storage-keys.md) document outlines what keys can possibly be used for asset storage. These should drive the bulk of the delete logic, dependant on the type of asset. In addition to that we'll need to:

* Raise an SQS notification (or SNS->SQS) when asset is deleted. We could use `IAssetNotificationSender` to raise them. This is called but just logs the delete action.
* Delete orchestrated asset from NAS storage (ie lustre). This negates above statement about using a Lambda - it'll need to run on an instance with NAS mounted.
* Invalidate Varnish cache. We should be able to use [varnishadm](https://varnish-cache.org/docs/3.0/reference/varnishadm.html) for this but we need to be careful to not expose this to public traffic. Varnish could be caching a number of items depending on the item type. May need changes to varnish image.
* Invalidate CDN cache - this should be a configurable option.
* _Ideally_ named query projections that contain this item. This will require some investigation as to how best to handle this as there are so many permutations of NQ results. It may require additional storage of which NQ projections contain which keys.

**Comment by donaldgray** [comment]
Deleting named queries need to raise a delete notification as it could result in the deletion if a number of generated NQ projections #540

**Comment by tomcrane** [comment]
## Acceptance Criteria

MVP

 - [ ] The DeleteHandler application is running in protagonist environment and listening to the SQS
 - [ ] Protagonist is raising SNS notifications for a DELETE operation on any asset
 - [ ] When DeleteHandler gets a message:
   - [ ] Delete orchestrated asset from NAS storage (ie lustre)
   - [ ] Invalidate Varnish cache (see #nn)
   - [ ] Invalidate CDN cache (not configurable for MVP)
  
Invalidation of stored NQ projections is not MVP.
