### ISSUE TITLE
Auth0 Discovery Application

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#278]
Create a very simple standalone .NET web app that is an Auth0 client, and deploy it into the DLCS estate.

There's probably an existing template app on the Auth0 site we can use straight off.
Like https://auth0.com/docs/quickstart/webapp/aspnet-core-2.

We connect this to Wellcome's Auth0, so it's a client.
We tweak the app so that it just prints out what we think are the user's "roles" - the claims/strings/whatever we are interested in for DLCS purposes.

The important part of this is not the OAuth2 flow or whatever - which is a given - it's the role acquisition. Or claims, in Auth0.

DLCS doesn't care who the user is. All it's interested in is matching claims to role data for assets. 

We test with logins ourselves but can also ask Wellcome people to confirm what they see when they log in to this app - e.g., archivists, librarians, other staff members, regular Sierra account holders.

We look at how we obtained those roles from Wellcome's Auth0, and use this to decide whether DLCS should be a **direct client of Wellcome's Auth0**, or whether it should use the DDS as a bridge as previously (initially to CAS, currently directly to Sierra).

I suspect it should be a direct client, but it should do this, if possible, without a specific dependency on Auth0. Can it obtain claims in a standardised way via OIDC, with assistance from claims-mapping config?

Make this a standalone app for simplicity; we can then work out how to apply it within DLCS.

**Comment by tomcrane** [comment]
For reference:

https://github.com/dlcs/protagonist/blob/develop/docs/rfcs/005-Access-Control.md

This shows the Role Provider as a separate service (e.g., Wellcome DDS acting as the Role Provide to the DLCS).
We expect integrators to implement the role provider, to bridge the DLCS to their auth system, whatever that might be.

The Role Provider returns the Role URIs the DLCS holds against its assets (for Wellcome DDS, it was the Role Provider that put them there at registration time).

If the DLCS is a direct OAuth2 / OIDC client of an auth provider, the roles/claims are unlikely to come back in the form of DLCS URIs, so they need to be mapped.

Distinct Role Provider Pros

 - simpler protocol
 - can provide the exact URIs the DLCS expects
 - can bridge to ANY form of auth

Cons

 - extra layer in the architecture
 - very similar to OAuth2 so why not go direct?

**Comment by donaldgray** [comment]
Deployed test application to https://auth-test.wellcomecollection.digirati.io, currently using Staging tenant.

Associated PRs:
* https://github.com/wellcomecollection/iiif-builder/pull/180
* https://github.com/wellcomecollection/iiif-builder-infrastructure/pull/42

**Comment by donaldgray** [comment]
Closing ticket as deployed for testing
