### ISSUE TITLE
"SpecialServer" routing for full requests

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#286]
Add image routing for "SpecialServer" - this is an alternative configuration of Cantaloupe that allows images to be streamed and served directly from S3 without the need for orchestration.

This can be done for `/full/` requests - do we want to handle requests above a certain size too. 

* Configurable? e.g. `/!1500,1500/` and above? 
* Or a proportion of the size (90% and above)

**Comment by tomcrane** [comment]
Requires #30
