### ISSUE TITLE
Improve handling of ImageOptimisationPolicies

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#324]
When ingesting an image we can specify an `ImageOptimisationPolicies`. We need to revisit this area and decide how best to handle.

An `ImageOptimisationPolicy` is a mapping of `<id>:<technical-details>`. This allows an API consumer some degree of control over how an asset is ingested.

The value in the `<technical-details>` element is dependant on the downstream derivative handler, e.g.:
* For Audio + Video assets `<technical-details>` is a comma delimited list of ElasticTranscoder formats to transcode source to.
* For Images it is which [pre-defined template](https://github.com/dlcs/appetiser/blob/master/app/jp2/kdu.py#L49-L69) to use in Appetiser.

We need the following functionality for `ImageOptimisationPolicies`
* As an admin user I can go in and configure as many globally available presets as I like, which correspond to args. We will need to decide how best to map these to values that appetiser can understand - ideally we don't want to pass full kdu_compress argument list.
* As a customer API consumer I can get a list of named presets (e.g. https://api.dlcs.io/imageOptimisationPolicies) - though not what the actual args are (implementation detail)
* As a customer API consumer I can declare what setting I want in the batch/asset payload
* As an admin portal user I can define argument list and test them out.

**Comment by tomcrane** [comment]
Also dependent on the particular JP2 processor - e.g., you can't have a preset called "JP2 Best Quality" with a kdu-specific set of params and then swap out the processor for OpenJPEG. So maybe there's an extra layer - this applies to AV too, where we might use an alternative to Elastic transcoder.

preset-friendly-name => dictionary of implementation keys => actual args

```
"jp2-super": {
   "kdu": "blah params blah",
   "openjpeg": "foo args bar"
},
"hls-max": {
   "aws-elastic": "xxx ccc",
   "ffmpeg": "xyz abc"
}
```

**Comment by donaldgray** [comment]
Superseded by https://github.com/dlcs/protagonist/issues/489
