### ISSUE TITLE
Enforce restrictions on Asset IDs

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#340]
Currently these are any string (although see https://github.com/dlcs/protagonist/issues/323)

But we would prefer them to not be susceptible to corruption through escaping when they appear in URLs.

This is related to https://github.com/wellcomecollection/docs/pull/30

The DLCS needs to enforce rules and reject asset IDs that break them - but how restrictive do we want to be? As restrictive as archivematica rules mentioned in that RFC?

And what do we do about existing non-compliant assets?

**Comment by donaldgray** [comment]
As an initial restriction we will prevent _new_ ids:
* That start with `v*` as these are optionally part of a path (we currently support `v2` and `v3` on paths for images and manifests but this could be expanded later so protect against `/v\d/`.
* That contain slashes or spaces - these need to be URL safe
* Any other URL unsafe characters?

We need to support GET / PUT / PATCH etc requests for _existing_ images - validation is for new images only.

**Comment by tomcrane** [comment]
Configuration includes a string that contains the permitted characters, and also a flag to enable:

 - no restrictions
 - restriction for new assets but allow updates of existing
 - fail for updates too

The DLCS should not normalise / sanitise any IDs - it can only reject. It's for the caller to ensure the IDs are valid.
