### ISSUE TITLE
Further validation in `AssetPreparer`

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#341]
This new class prepares assets for insertion in the DB, which includes some validation. 

It could do more validation than currently though.
It could also allow some updates that Deliverator does not.

It could also validate dimensions (although it's usually Engine that sets them rather than end users)
 - validate combinations of dimensions - `w,h | w,h,d | d | <none>`

**Comment by donaldgray** [comment]
Note - some of this will be covered by #393, which introduced the 'no-transcode' concept. Now `w,h,d` can be set if the ImageOptimisationPolicy = 'none'.

**Comment by tomcrane** [comment]
I think this issue is superseded by #393 and the fact that engine sets dimensions (is error when user tries to modify them)
