### ISSUE TITLE
More granular config than "FullBucketAccess"

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#352]
When ingesting Timebased assets, deliverator has a `"FullBucketAccess"` boolean config setting. This is part of the `"CustomerOverrides"` config block for engine.

This value:
* when `true` _and_ an s3 based asset is being ingested (via `s3-ambient` origin strategy) then the AWS SDK is used to do a direct S3 bucket to bucket copy, with the DLCS bucket being the input for ElasticTranscoder. At a minimum, the DLCS requires `s3:ListBucket` and `s3:GetObject` on the source to copy bucket to bucket.
* when `false` _or_ not `s3-ambient` then the file is downloaded to local disk first and then uploaded to S3.

Ideally we'd have more granular access than a customer wide setting, possibly rolled into CustomerOriginStrategy.

**Comment by tomcrane** [comment]
This config needs to be exposed by the API first and then reflected in the portal

**Comment by donaldgray** [comment]
`"FullBucketAccess"` isn't a concept anymore, it was removed as part of the work for refactoring optimised origin logic.

If COS is S3 and Optimised then `"FullBucketAccess"` is assumed (ie we can't have an optimised S3 origin without 'full' access).

See https://github.com/dlcs/protagonist/commit/58c575792f699712126d2766d95301cba2f494ea
