### ISSUE TITLE
Lustre: determine if a filesystem walk is needed to build an initial view

### ISSUE THREAD

**Issue by garyttierney** [dlcs/protagonist#374]
When attaching to an existing Lustre volume the metadata log might already have purged the earliest records. so we'd need to do a regular filesystem walk to figure out the last access times. It may be possible to leverage other existing metadata from Lustre to decide whether or not the metadata log is fresh enough

**Comment by garyttierney** [comment]
Implemented in lustre-watcher (https://github.com/dlcs/lustre-watcher/pull/1). The filesystem will always be scanned on boot to build the initial view.

**Comment by tomcrane** [comment]
Closed by https://github.com/dlcs/lustre-watcher/pull/1
