### ISSUE TITLE
Raise notification when Asset modified

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#378]
This is stubbed as `IAssetNotificationSender.SendAssetModifiedNotification` and currently logs a message without a notification being raised.

**Comment by tomcrane** [comment]
https://github.com/dlcs/protagonist/blob/5f2017fa9dd03024289ef21f41fe48a797e8b1e5/src/protagonist/API/Infrastructure/Messaging/AssetNotificationSender.cs#L71

We have an AssetModified topic already with attribute-based routing

Acceptance

- When asset created or updated, message is sent to AssetModified topic
- message includes asset; update has both old and new asset
- attribute 

https://github.com/dlcs/protagonist/blob/d3e5ed3a8f0587d04eb450cd9f75981841ae7780/src/protagonist/DLCS.AWS/SNS/TopicPublisher.cs#L27

https://github.com/dlcs/protagonist/blob/6e26469b453f1158514718d4a094f0d1bb292030/src/protagonist/DLCS.AWS/SNS/ITopicPublisher.cs#L20

The string messageContents should a JSON object containing:

- The created or updated asset - after update
- The pre-change asset if an update
- customer path element (id is in the asset) - useful for invalidating caches without further lookup
