### ISSUE TITLE
Need to refresh customer after ApiKey created

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#388]
I created an ApiKey for a customer using admin credentials but then couldn't log in as that customer because their details were already in the cache and the cached `Customer` didn't have the new api keys set.

**Comment by tomcrane** [comment]
Task is to refresh the API's cached customers on any CUD operation on customers or their keys

OK to wipe the whole thing from ASP.NET memory - Cache.Remove(...)

## Acceptance criteria

Any change to a customer or its keys is immediately reflected in API calls (e.g., using a key)
