### ISSUE TITLE
Enable editing ThumbnailPolicy for images

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#448]
Allow editing ThumbnailPolicy for images.

This will trigger a reingest. We will also need to clean up any derivatives or assets that are no longer required (this will be part of #430).

**Comment by tomcrane** [comment]
Question is whether we do anything on this before finalising API approach to delivery channels.

Unless any shared service customers need it I think not.

So, possibly obsolete.

**Comment by tomcrane** [comment]
Closing as obsolete, superseded by full delivery channel specification
