### ISSUE TITLE
Orchestrator proxy behaviour for open AV derivatives

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#452]
Currently if an AV output of Elastic Transcoder is open (no auth), Engine will update the DLCS storage bucket permission on just that output (the one or more keys for its derivatives) to make them public, and Orchestrator will issue a redirect to the AWS S3 bucket URL of that derivative.

This takes traffic load away from Orchestrator and onto AWS.

We could either decide to continue with the current behaviour, or have Orchestrator proxy the request "properly", no redirect.

The argument in favour:
 - It maintains the URL
 - We now have a proper reverse proxy in place rather than hand-rolling byte-copying chunks
 - A change to maxUnauthorised is just a patch of a data field, it doesn't require Engine to be invoked

The argument against:
 - It's still traffic that Orchestrator now has to handle
 - will all the byte range requests work properly? (essential)
 
We have to proxy for authed requests anyway but should we do it for all AV requests?

**Comment by tomcrane** [comment]
(for now keep the redirect behaviour, but if we implement it we can undo this change: https://github.com/dlcs/protagonist/pull/453)

We can also make the DDS revert to a regular batch patch, undoing this change:
https://github.com/wellcomecollection/iiif-builder/commit/fa096f43a5460e649f930771119028b775638490

**Comment by donaldgray** [comment]
Note - removed code comment related to this ticket. 

If we implement orchestrator proxying the requests, rather than s3 redirecting, we can remove setting `requiresReingest = true` if `MaxUnauthorised` changes. Instead we'd need to invalidate the Orchestrator cache.

**Comment by donaldgray** [comment]
#473 implemented proxying open AV files through Yarp.
