### ISSUE TITLE
Investigate missing batches

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#459]
This PR is supposed to fix a problem with assets referencing batches that don't exist:

https://github.com/dlcs/protagonist/pull/455

It's not clear why this problem is happening and needs to be re-created and tested.

**Comment by donaldgray** [comment]
Unable to reproduce. Possibly fixed by https://github.com/dlcs/protagonist/pull/466

**Comment by donaldgray** [comment]
Closing for now, can reopen if still appears
