### ISSUE TITLE
Allow image-service and/or thumbs to be provided for an image

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#460]
Currently an image asset registered with the DLCS will gain both an image-service (`/iiif-img/`) and have thumbnails generated (`/thumbs/`). We should have a method of controlling whether only 1 of these, or both, are available.

This could be handled in a couple of different ways:
* Via a `thumbs` delivery-channel (see below).
* Via a `no-op` thumbsOptimisationPolicy. If we choose this option we would need to better handle the `no-op` imageOptimisationPolicy (rather than use it as a default for images that are only available on file delivery channel).

Some considerations where thumbs can affect:
* What is uploaded to S3
* How the request to Appetiser is made + how output is handled
* What ImageStorage values we store in DB
* How `/iiif-img/` requests are handled (can we use thumbs-optimisations)
* Can image be used in PDF/Zip projections (as there is now low.jpg)
 
The original plan for #393 included an explicit "thumbs" delivery channel, as mentioned in [RFC-009 Asset Family Improvements](https://github.com/dlcs/protagonist/blob/develop/docs/rfcs/009-asset-family-improvements.md#asset-delivery-channel). This would allow us to provide thumbs and/or image-services for an image asset. This was dropped from the ticket to ease implementation and speed up delivery but should be added back in.

Related to this is https://github.com/dlcs/appetiser/issues/13, Appetiser will error if no thumbnail sizes are provided. A hack to this is to supply a list of 1 known size (e.g. `new[] { 100 }`) and then ignore the output but this isn't ideal.

**Comment by tomcrane** [comment]
See https://github.com/dlcs/protagonist/issues/73#issuecomment-1621532564 for an overview of the approach.

**Comment by tomcrane** [comment]
I think this is now superseded by the updated description in #489

**Comment by tomcrane** [comment]
superseded by #489
