### ISSUE TITLE
Improve file delivery handling

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#462]
PR #431 reworked file handling delivery as part of work to introduce delivery-channels.

`/file/` paths are handled as a "normal" web request (ie not proxied) - it will stream the origin file from either DLCS storage or client storage if optimised*. This will work okay for smaller files but not necessarily for larger AV files.

We should investigate how best to handle better streaming of the file, for example handling [range headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) to support actions like scrubbing in a viewer. 

One option would be using Yarp to proxy as this is how we currently handle AV ranged requests.

_\* for backwards compatibility with Deliverator we may need to stream from a non-s3/non-optimised source._

**Comment by tomcrane** [comment]
Yarp seems the way to go here?

**Comment by donaldgray** [comment]
Closing issue - files are now proxied through Yarp like AV https://github.com/dlcs/protagonist/pull/473
