### ISSUE TITLE
What happens when a legacy API call is supported?

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#463]
With the removal of asset family in #431, `mediaType` is now a lot more important. If there is no `mediaType` provided during ingest the DLCS will throw a 400 exception.

For backwards compatibility we may need to allow `mediaType`-less ingests. If that's the case a config value should enable/disable this per customer and some sensible defaults configured. E.g. looking at URL and trying to workout from the file name.

**Comment by tomcrane** [comment]
> per customer

(v important!) - and customer can control this in portal.

**Comment by donaldgray** [comment]
Regarding above comment, see https://github.com/dlcs/protagonist/issues/528

**Comment by tomcrane** [comment]
If acceptLegacyApiCalls = true:


# MediaType

* By API, using (for example) file extension?
* By Engine, using mediaType of HTTP response from origin?

If the latter and there is missing mediaType and acceptLegacyPayloads=true then:

* API sets a dummy mediaType "dlcs/unknown" for Engine to correct.

When processed by Engine:

if "dummy" mediaType (set by API)
 - work out mediaType from origin HTTP response
 - if still unknown, or `application/*` or similar, use https://github.com/dlcs/protagonist/blob/main/src/protagonist/DLCS.Core/MIMEHelper.cs

# MaxUnauthorised 

In API:

 - Replace any `0` with `-1` if roles is empty 
 
(this is also the release-day DB update)

# Delivery Channels / Family

In API (not engine):

If `origin` only supplied, assume it is an image
 - Set Family to `I`

(protagonist already implements the default delivery channels from here, whether family is `I`, `T` or `F`)
