### ISSUE TITLE
Periodically recalculate CustomerStorage and EntityCounters

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#467]
Over time these may get slightly out of sync - have a job that periodically recalculates to ensure they are kept up to date.

### EntityCounters

| type            | description                                                                          |
| --------------- | ------------------------------------------------------------------------------------ |
| space           | Count of space per customer. `Scope` and `Customer` are `customerId`                 |
| customer        | Count of customers in system. `Scope` and `Customer` are 0                           |
| customer-images | Count of images per customer. `Scope` is `customerId`, `Customer` is 0               |
| space-images    | Count of images per customer space. `Scope` is `spaceId`, `Customer` is `customerId` |

 - The job is a lambda on a timer 
 - The job iterates through all entity counters and runs the SQL that gives an accurate count
 - The job updates the counter row if inaccurate
 - The job logs to cloudwatch
 - The job notifies slack with a summary (in a single message not per counter!)

See: https://digirati.atlassian.net/wiki/spaces/DLCS/pages/3305242656/Resetting+Entity+Counters for example query to reset.

### CustomerStorage
 
 - The job is a lambda on a timer
 - The job SUMs the number of images, bytes used etc from the ImageStorage table
 - The job updates the CustomerStorage table per customer per space if inaccurate.
 - The job creates a CustomerStorage record where `Space=0`, this is the total for this customer.
 - The job logs to cloudwatch
 - The job notifies slack with a summary (in a single message not per counter!)

**Comment by tomcrane** [comment]
See is Wellcome is still going adrift
