### ISSUE TITLE
New Engine

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#48]
This is already in progress, see https://github.com/dlcs/protagonist/tree/engine-rework

**Comment by donaldgray** [comment]
As per initial comment, engine is in progress. However, at the time of writing this comment the [`engine-rework`](https://github.com/dlcs/protagonist/tree/engine-rework) branch is 84 ahead, 606 behind the develop branch and will need to be brought up to date.

Much of the code can be ported over as-is, some classes have already been ported over (e.g. some `OriginStrategy` implementations as part of Orchestrator work) and some implementations will need to be rewritten. The largest change is the introduction of EFCore to Develop - `engine-rework` is using Dapper. While `Dapper` will still work it is preferably, where possible, to update logic to use EFCore.

The following tickets relate to bringing the `engine-rework` branch up to date.
* #264 
* #265 
* #266 
* #267 
* #268 
* #269 
* #270

**Comment by donaldgray** [comment]
Closing - engine is implemented. Any specific issues can be addressed in new issues.
