### ISSUE TITLE
Do not write s.json if no jpgs are found

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#499]
When reorganising thumbnails an assumption is made that the jpgs will be present. This should be checked first to avoid writing an s.json that doesn't reflect what is actually there.

**Comment by donaldgray** [comment]
This is likely no-longer required - Protagonist has a dependency on `s.json` so once rolled out we can disable thum reorganising code (and remove implmementation for it).

**Comment by tomcrane** [comment]
Decision in refinement - not relevant any more!
