### ISSUE TITLE
Check for content-disposition header in Cantaloupe response

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#513]
This may be a non-issue and related to CantaloupeV4 only - need to verify behaviour in Cantaloupe5. 

It also looks to be related to using JPEGs as source, directly from S3, rather than JP2.

The `content-disposition` header is set and sets the filename to the S3 location where images are stored, e.g.:

```
content-disposition:inline; filename="s3___eu-west-1_dlcs-storage_2_8_B0004066.jpg"
```

We should strip this out, or replace it with the AssetId, if present.

**Comment by tomcrane** [comment]
This no longer happens in Cantaloupe 5
