### ISSUE TITLE
GET `/imageOptimisationPolicies` returning wrong `@id` value for global policies

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#525]
GET `/imageOptimisationPolicies` returns a list of imageOptimisationPolicies. ImageOptimisationPolicies can be customer specific, or global. If global they are assigned `customer=1` (Admin customer). 

This is rendering an `@id` property of `"https://api.dlcs.io/customers/1/imageOptimisationPolicies/audio-max"` rather than `"https://api.dlcs.io/imageOptimisationPolicies/audio-max"`. The former doesn't work as the API expects credentials to be provided when viewing a `/customer/{customerId}/` path, however the latter does.

We need to render the `@id` property _without_ customer if it's global but _with_ customer if it is customer-specific.

I suspect this is to do with the Hydra modelling and how it generates uri's.

**Comment by tomcrane** [comment]
## Acceptance criteria

 - GET `/imageOptimisationPolicies` returns only global policies - with no customer path
 - GET `/customers/{n}/imageOptimisationPolicies` returns the union of globals and your own ones - which means it can have a mixture of global paths and customer paths for the `@id`s of the policies
