### ISSUE TITLE
Return the Image Service URL as part of Image

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#54]
The Image (or rather, asset) record does not include the Image Service URL.
If you PUT a new image, and get an Image object in response, you still have to deduce what the IIIF Image API endpoint would be.

This should come back as part of the Image, as should the derivative URLs that would be made for AV items.

Even if the service or derivatives won't be ready yet.

**Comment by donaldgray** [comment]
Closing - API response contains `imageService` and `thumbnailIimageService` properties in response. 

```json
{
    "@context": "https://api.dlcs.digirati.io/v2/contexts/Image.jsonld",
    "@id": "https://localhost:8080/customers/7/spaces/4/images/sample",
    "@type": "vocab:Image",
    "id": "sample",
    "space": 4,
    "imageService": "https://localhost:8081/iiif-img/7/4/sample",
    "thumbnailImageService": "https://localhost:8081/thumbs/7/4/sample",
}
```
