### ISSUE TITLE
Support SFTP origin strategy

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#570]
Deliverator supports an `sftp` origin strategy and this has been stubbed out in Protagonist as `DLCS.Repository.Strategy.SftpOriginStrategy` and the dependency is wired up with resolver etc https://github.com/dlcs/protagonist/blob/9850804e6ade52bc3bfe3ab7a7a674cb53ff1a37/src/protagonist/DLCS.Repository/Strategy/DependencyInjection/ServiceCollectionX.cs#L39.

We need to implement `SftpOriginStrategy` and verify the rest of the plumbing around this works.

## Acceptance criteria

 - Needs an SFTP server running - could be AWS but $0.30 ph so be careful. Or a docker image on ECS. Or something.
 - If AWS it needs to be off all the time apart from specific testing - NOT just off outside of office hours.

**Comment by donaldgray** [comment]
Related: #541

**Comment by tomcrane** [comment]
Can use for testing: 
https://aws.amazon.com/about-aws/whats-new/2018/11/aws-transfer-for-sftp-fully-managed-sftp-for-s3/

**Comment by JackLewis-digirati** [comment]
NOTE: this ticket should be tested using a large file
