### ISSUE TITLE
Info.json should not advertise tile sizes > maxUnauthorised

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#580]
Base `info.json` files are generated from the downstream image-server (ie Cantaloupe) and then updated with any additional services such as auth before being saved in S3.

We overwrite the [`"sizes"`](https://iiif.io/api/image/3.0/#53-sizes) property with the sizes of pre-generated thumbs.

We also need to updated the [`"tiles"`](https://iiif.io/api/image/3.0/#54-tiles) property if the suggested tiles size is greater than `maxUnauthorised` value for the asset.

The resulting tile size should always be a power of 2 and smaller than `maxUnauthorised`.

The relevant place in code to make this change is `InfoJsonConstructor` - this is called prior to saving the info.json in S3.

**Comment by tomcrane** [comment]
https://github.com/dlcs/protagonist/blob/ae437916326cbb2ad34fe0823ad73cdbdcbdb218/src/protagonist/Orchestrator/Features/Images/ImageServer/InfoJsonConstructorTemplate.cs#L121

https://github.com/dlcs/protagonist/blob/7d220d53fa6331484ab6200f0a9e52f0de8349b5/src/protagonist/Orchestrator/Features/Images/ImageServer/InfoJson2Constructor.cs#L59

(and InfoJson3Constructor)

**Comment by tomcrane** [comment]
Acceptance:

 - Info.json does not suggest a tile size that orchestrator won't serve
 - but we never reduce a cantaloupe-suggested tile size for any other reason
