### ISSUE TITLE
Improve Batch ingest performance

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#595]
We have noticed an increase in timeouts when ingesting large batches (100 images) from Wellcome. These timeouts are occurring in the HttpClient making requests and is set at 30s. Something that might have a bearing on this is that all batches are for the same customer and, for the most part, the same space.

Looking at logs for 1 particular item that was synching 2x100 image batches we saw the following for 2 requests R1 + R2 (the important part is `R2` stalls for 15secs, until `R1` is aborted.):
```
12:46:44.965, Request1 Received (R1)
12:46:44.979, Processing asset 2/5/0201.jp2 (R1)
12:46:45.701, Processing asset 2/5/0202.jp2 (R1)
...R1 churning..
12:47:01.893, Processing asset 2/5/0255.jp2 (R1)
12:47:01.951, Request2 Received (R2)
12:47:01.977, Processing asset 2/5/0101.jp2 (R2)
12:47:02.330, Processing asset 2/5/0256.jp2 (R1)
...R1 churning while R2 waiting...
12:47:14.989, An error occurred using a transaction. (R1)
12:47:14.990, An exception occurred in the database while saving changes for context type 'DLCS.Repository.DlcsContext'. (R1)
12:47:14.991, HTTP POST /customers/2/queue/priority responded 500 in 30026.7956 ms (R1)
12:47:14.991, Processing asset 2/5/0297.jp2 failed, aborting batch. Error: 'The operation was canceled.'" (R1)
12:47:15.252, Processing asset 2/5/0102.jp2 (R2)
...R2 starts again...
12:47:32.138, An error occurred using a transaction. (R2)
12:47:32.140, Processing asset 2/5/0157.jp2 failed, aborting batch. Error: 'The operation was canceled.'" (R2)
12:47:32.140, An exception occurred in the database while saving changes for context type 'DLCS.Repository.DlcsContext'. (R2)
12:47:32.149, HTTP POST /customers/2/queue/priority responded 500 in 30198.6091 ms (R2)
```

The implementation of batch processing in deliverator was to process 1 item at a time. This included notifying Engine. This avoided locking the database and meant that images were processed as quickly as they could be _however_ it came at the cost of half-processed batches (e.g. if image 59 of a 100-image batch failed it meant there may be 58 items in the DLCS and the last 42 wouldn't be).

Protagonist takes the approach of processing all items in the API together and notifying the engine in bulk if all of them save okay. This process needs looked at to make improvements. It isn't particularly efficient as it processes each asset in turn, including loading from database (so it makes a _lot_ of DB calls) all wrapped in a transaction. The transaction makes it easier to re-use existing classes but looks to be the issue here. We are using `IsolationLevel.ReadCommitted`, which could be the issue as the EntityCounter + Queue tables are updated per asset (IIRC - need to verify).

Process is currently
* start transaction
* create batch
* for..each
  * load asset
  * `PrepareAsset()` (sync incoming changes with default asset, or existing asset)
* `dbContext.Save()`
* `transaction.Commit()`
* send all to engine (via SQS, batches of 10)

But it could be something like:
* load all assets (`where id in (...)`)
* for..each 
*   `PrepareAsset()` (but don't call `dbContext.Save()`)
* `dbContext.Save()` (EF commits all changes - any `PATCH` requests made while preparing could be overwritten)
* send all to engine (as above - batches of 10)

**Comment by donaldgray** [comment]
Specific issue at Wellcome caused by a rogue long running query

**Comment by tomcrane** [comment]
OK, going to close this!
