### ISSUE TITLE
Create a template for pull requests

### ISSUE THREAD

**Issue by JackLewis-digirati** [dlcs/protagonist#596]
When creating a pull request, there is no standardized template for how to write a description for them.  This  makes writing a description for more vague than it should be.  GitHub has the ability to setup templates for pull requests to simplify creating them.

Additionally, this template should contain a checklist of steps that need to be completed once a pull request is raised. This should include:

- deploy to AWS
- test AWS deployment
- verify functionality is working as intended

It might also be worth looking at adding the [task list complete](https://github.com/marketplace/task-list-completed) app to GitHub to force the checklist to be ticked off before the PR can be merged

**Comment by donaldgray** [comment]
I don't think it'll have any bearing on what we do but just flagging that only Digirati staff have access to deploy to AWS.

**Comment by tomcrane** [comment]
#wontfix
