### ISSUE TITLE
Fix space cache key

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#598]
There are 2 `GetSpace` methods in `SpaceRepository` - one for fetching by name and one for id. Internally they both call `GetSpaceInternal`. The former passing -1 for Id.

`GetSpaceInternal` caches using `var key = $"space:{customerId}/{spaceId}";`

Searching for space with name "foo" then later for "bar" could result in "foo" space being returned for "bar" as it'll be cached for spaceId -1. This could result in a PUT or PATCH failing as it looks like the name will already exist.

Also searching by Id uses `.AsNoTracking()` but name doesn't - these should be consistent.

**Comment by tomcrane** [comment]
https://github.com/dlcs/protagonist/blob/cffa745e3bb19598b600dd1bdd1e01064df113a6/src/protagonist/DLCS.Repository/Spaces/SpaceRepository.cs#L115

- Cache key should be name when name was asked for, id when id was asked for.
- This might result in more keys and the same space cached under its two different keys, but that's OK
