### ISSUE TITLE
Modify DB Schema: add tables for delivery channels

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#618]
- Add a new table to store per-channel policies (DeliveryChannelPolicies).
 - Add a new joining table (ImageDeliveryChannels)

An asset can have [0..n] delivery channels with the fields `channel` and `policy`.
 - `channel` is the string `iiif-img|thumbs|iiif-av|file`
 - `policy` is a reference to either a system policy (e.g., `use-original`), or to a DeliveryChannelPolicy that belongs to the customer, which appears in the API as a URI but in the DB is some referential link.

A customer or a Space can have [0..n] delivery channels with the fields `channel`, `policy` and `mediaType`. These are matched on mediaType to assets when assigned by the default mechanism and new per-asset delivery channels created. They are **templates** for the asset delivery channels above.

So we have template DeliveryChannelPolicy objects that get copied and given to new customers as their own set of DeliveryChannelPolicy objects that they can reference, and tweak.

We have template DeliveryChannel objects that a Customer or Space has as members of `defaultDeliveryChannels` - we assign a selection to `customer.defaultDeliveryChannels` on customer creation, they reference the copied DeliveryChannelPolicy objects above (or "globals" like `use-original`). These are only used by the default matching process to populate an Asset's delivery channels when the API caller doesn't specify any.

And we have the "real" DeliveryChannel objects that belong to an asset, either specified explicitly by the API caller, or assigned through default logic by matching one of the above template DeliveryChannel objects, and _copying_ it.

Do we have enough tables?

**Comment by tomcrane** [comment]
Acceptance criteria

1. A schema for the tables (design suggestion - can be put here)
2. Agree that those tables (probably 2) can store what is required by the docs
3. Add those tables to the DB
4. Add EF domain objects to the context

**Comment by JackLewis-digirati** [comment]
started an rfc here for the database design - https://github.com/dlcs/private-protagonist/blob/feature/deliveryChannelDatabase/docs/rfcs/012-delivery-channels-database.md

**Comment by tomcrane** [comment]
## WIP possible tables

_link between asset and its deliverychannels+policies_

ImageDeliveryChannels
---------------------
ImageId
DeliveryChannelPolicyId
channel



_policies+DCs available to my assets_

DeliveryChannelPolicy
------------
id
channel ("image")
name ("standard", "my-thumbs", "default")
displayName
channel ("image")
mediaType  ("image/*", "image/jp2")
policyData (["none"],  ["video-mp4-720p"], ["use-original"])
configurable?
customer (0, 37)




_For allocating defaults on incoming API payloads that lack any dc info and don't explicitly say "channel": "none"_

DefaultDeliveryChannelPolicies
--------------------------
DeliveryChannelPolicyId
customer (37   --
space (0, 99, 123)
mediaType?

**Comment by tomcrane** [comment]
Donald comments:

I think these are the questions:
 
API
- If deliveryChannels specified:
  - how are these saved? where do we save in db?
- If deliveryChannels not specified
  - how do we identify what policies/channels to use?
  - how are these saved? where do we save in db?
- When asset requested - how is the Hydra model populated?
 
Engine (by the time it picks up API will have done it's thing + record will be populated)
- How does engine identify which workers to invoke (file/image/av)
- How does each worker know what to do (which thumbs, what transcode targets etc)
 
Orchestrator
- When a request is received, how does Orchestrator determine if asset is available on that channel (this should be as efficient as poss)

that bottom table (DefaultDeliveryChannelPolicies) is a replacement for https://github.com/dlcs/protagonist/blob/bd9c0f3307cdc41aec603c73ed2b93ce4bb07c75/src/protagonist/API/appsettings.json#L29-L56
