### ISSUE TITLE
Create "global" DeliveryChannelPolicies and DefaultDeliveryChannels

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#619]
*Edited* 2024-01-24

See https://digirati.slack.com/archives/C110R7N5Q/p1706109557121819

We need the initial DeliveryChannelPolicy data:

```
     |--------- (constraint) ------------|

| id | Customer | Channel  | Name          | DisplayName                  | System | PolicyCreated | PolicyModified | PolicyData                                              |
|----|----------|----------|---------------|------------------------------|--------|---------------|----------------|---------------------------------------------------------|
| 1  | 1        | iiif-img | default       | The default image policy     | 1      | 2024-01-01    | 2024-01-01     | null                                                    |
| 2  | 1        | iiif-img | use-original  | Use original at Image Server | 1      | 2024-01-01    | 2024-01-01     | null                                                    |
| 3  | 1        | file     | none          | No transformations           | 1      | 2024-01-01    | 2024-01-01     | null                                                    |
| 4  | 1        | iiif-av  | default-audio | The default policy for audio | 0      | 2024-01-01    | 2024-01-01     | [\"audio-aac-192\"]                                     |
| 5  | 1        | iiif-av  | default-video | The default policy for audio | 0      | 2024-01-01    | 2024-01-01     | [\"audio-aac-192\"]                                     |
| 6  | 1        | thumbs   | standard      | An example thumbnail policy  | 0      | 2024-01-01    | 2024-01-01     | [\"!1024,1024\",\"!400,400\",\"!200,200\",\"!100,100\"] |

```

 - DCPs with `system=1` are not copied to customers. They are also referred to in API, both incoming and outgoing, just by their `name`. They do not have `policyData`, the DLCS knows what to do with them.
 - DCPs with `system=0` are duplicated to new customers, thereby acquiring their own URIs and allowing customers to modify them.

If we create Customer 99, three new rows will appear in this table:

```
| 7  | 99       | iiif-av  | default-audio | The default policy for audio | 0      | 2024-01-01    | 2024-01-01     | [\"audio-aac-192\"]                                     |
| 8  | 99       | iiif-av  | default-video | The default policy for audio | 0      | 2024-01-01    | 2024-01-01     | [\"video-mp4-720p\"]                                     |
| 9  | 99       | thumbs   | default       | An example thumbnail policy  | 0      | 2024-01-01    | 2024-01-01     | [\"!1024,1024\",\"!400,400\",\"!200,200\",\"!100,100\"] |

```

We also need a set of template `defaultDeliveryChannels` on Customer 1:

```
| Customer | Space | MediaType       | DeliveryChannelPolicyId |
|----------|-------|-----------------|-------------------------|
| 1        | 0     | "image/*"       | 1                       | 
| 1        | 0     | "image/*"       | 6                       | 
| 1        | 0     | "video/*"       | 5                       | 
| 1        | 0     | "audio/*"       | 4                       | 
| 1        | 0     | "application/*" | 3                       |
```

These are all used to create 5 new rows in defaultDeliveryChannels for a new customer. Those whose DeliveryChannelPolicyId  is for a system=1 DeliveryChannelPolicy reference the original, unique customer 1 row, and those whose DeliveryChannelPolicyId  is for a system=0 DeliveryChannelPolicy reference the customer-specific rows. So if we add a customer 99, we end up with 5 new rows in this table:

```
| 99       | 0     | "image/*"       | 1                       | 
| 99       | 0     | "image/*"       | 9                       | 
| 99       | 0     | "video/*"       | 8                       | 
| 99       | 0     | "audio/*"       | 7                       | 
| 99       | 0     | "application/*" | 3                       |
```

Note that customers don't get given the "use-original" as a default - that can't work as there would then be two possible `iiif-img` channel+policy combinations.

In the above, the initial defaultDeliveryChannels uses two global/system policies and three policies that belong to the user, that they can edit. There are two that match on `image/*` but they are for different channels.

An incoming image/tiff for customer 99 that didn't specify any deliveryChannels would be given:

```
  "deliveryChannels": [
    {
      "@type": "vocab:DeliveryChannel",
      "channel": "iiif-img",
      "policy": "default"
    },
    {
      "@type": "vocab:DeliveryChannel",
      "channel": "thumbs",
      "policy": "https://api.dlcs.io/customers/99/deliveryChannelPolicies/thumbs/standard"
    },
```

There is also a one off DB-migration task, and that is to apply this new row creation in both tables to all EXISTING customers, so they get the data they would have if created with this mechanism already in place.

These will act as a template and be copied (not referenced) for new customers when a new customer is created.

https://deploy-preview-2--dlcs-docs.netlify.app/api-doc/delivery-channels#preset-policies

**Comment by tomcrane** [comment]
Is this a DB migration?

**Comment by JackLewis-digirati** [comment]
currently I've got something like the follow - 


| Id | Name | DisplayName | Customer | Space | Channel | MediaType | PolicyCreated | PolicyModified | PolicyData |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | image-default | the default image policy | 1 | 0 | iiif-img | image/\* | 2024-01-22 17:14:44.971000 +00:00 | 2024-01-22 17:14:56.319000 +00:00 | \["default"\] |
| 2 | image-none | No optimisation/transcoding | 1 | 0 | iiif-img | image/\* | 2024-01-22 17:15:50.282000 +00:00 | 2024-01-22 17:15:52.098000 +00:00 | \["none"\] |
| 3 | image-use-original | Use original for image-server | 1 | 0 | iiif-img | image/\* | 2024-01-22 17:16:31.906000 +00:00 | 2024-01-22 17:16:42.077000 +00:00 | \["use-original"\] |
| 4 | audio-default | The default policy for audio | 1 | 0 | iiif-av | audio/\* | 2024-01-22 17:20:36.803000 +00:00 | 2024-01-22 17:20:37.906000 +00:00 | \[ "audio-aac-192" \] |
| 5 | video-default | The default policy for video | 1 | 0 | iiif-av | video/\* | 2024-01-22 17:21:39.292000 +00:00 | 2024-01-22 17:21:40.565000 +00:00 | \[ "video-mp4-720p" \] |
| 6 | file-none | A default no-op policy for file | 1 | 0 | file | \* | 2024-01-22 17:23:37.759000 +00:00 | 2024-01-22 17:23:39.772000 +00:00 | \["no-op"\] |

**Comment by tomcrane** [comment]
## Acceptance criteria

 - [ ] The default data exists in the tables 
 - [ ] A new customer gets the .defaultDeliveryChannels
 - [ ] Those .defaultDeliveryChannels are processed by the DLCS to assign actual .deliveryChannels properties to assets that lack them
 - [ ] Assets that are passed in with an explict `none` channel do not get the defaults - see https://deploy-preview-2--dlcs-docs.netlify.app/api-doc/delivery-channels#the-none-channel

(this needs quite a lot of tests)

**Comment by tomcrane** [comment]
Question- 

Do we give/copy all customers the defaultDeliveryChannel for `file` that matches `*/*`?

```
| 99       | 0     | "*/*"        | 3                       |
```

Probably not, they have to turn this on - otherwise they might inadvertently be giving access to their master tiffs or whatever.

**Comment by tomcrane** [comment]
Where and when does the initial population of Customer 1 DeliveryChannelPolicies and DefaultDeliveryChannels happen?

 - This happens in a DB migration (not in the setup method)
 - It's a separate migration to the DB setup

**Comment by tomcrane** [comment]
Wellcome will end up with 4 custom thumbnail policies to choose from, but they will be created by a dynamic script reading what's there - we don't hard-code these.

 - `[ "!1024,1024" , "!400,400", "!200,200", "!100,100" ]`
 - `[ "!1000,1000" , "!400,400", "!200,200", "!100,100" ]`
 - `[ "!200,200", "!100,100" ]`
 - `[ "!100,100" ]`

The first of these happens to be the default that is applied when no DCs are specified on an incoming asset - how does the script know that this is the default? - from the name of the policy.
