### ISSUE TITLE
Flag to not transcode time-based media

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#62]
If the customer has already web-optimised a video file, we don't want to transcode it again.

How do we signal that this is the case?

But we might still want to the DLCS to provide additional derivatives.

 - use the mp4 I give you, and make a webm via policy 37.

(Wellcome DLCS MP4s are coming out bigger than the source, both in pixel dims and file size).

**Comment by tomcrane** [comment]
Also need to measure asset when not transcoded, as in #62

**Comment by donaldgray** [comment]
The caller should tell DLCS how to handle it.

At this point, we _don't_ want DLCS to be smart around trying to identify what to do. E.g. if it gets an mp4 and is to create an 720p mp4 then don't do it if it's already 720p but do it if it's 1080p.

If we use an image-optimisation policy for this then we still want to be able to declare multiple outputs, one of which is the current file.
