### ISSUE TITLE
Implement default deliveryChannels and retire DLCS:IngestDefaults appSetting

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#625]
Stop using “DLCS:IngestDefaults” from appsettings and use the customer.defaultDeliveryChannels and space.defaultDeliveryChannels to match.

Therefore, handle ‘minimal’ DeliveryChannel payloads.

 - no delivery channels at all: match on mediaType, from most specific to least (image/tiff before image/*)
 - delivery channels with no policy, either as objects ~or just strings~: match on mediaType and channel

This may match multiple delivery channels but only one each. e.g., you could follow the rules and get

```
[ 
   {"channel": "iiif-img", "policy": "default"},
   {"channel": "thumbs", "policy": "https://.../superthumbs1"},
   {"channel": "file", "policy": "none"}
]
```

but you couldn't end up with:

```
[ 
   {"channel": "iiif-img", "policy": "default"},
   {"channel": "thumbs", "policy": "https://.../superthumbs1"},
   {"channel": "thumbs", "policy": "https://.../my-special-thumbs"},
   {"channel": "file", "policy": "none"}
]
```

Only one combo per channel. If my-special-thumbs only matches image/tiff but superthumbs1 matches image/*, then this would be, for an asset registered as image/tiff:

```
[ 
   {"channel": "iiif-img", "policy": "default"},
   {"channel": "thumbs", "policy": "https://.../my-special-thumbs"},
   {"channel": "file", "policy": "none"}
]
```

Can we validate your set of defaults to prevent this before it gets to asset registration?
Space defaults (if you have them) combine with Customer defaults but override them.

We could prevent you adding in defaults that would result in two matches.

**Comment by tomcrane** [comment]
(Donald)

> *Could we release at this point? Small functional change in that we take new format of policies

**Comment by tomcrane** [comment]
This is large because it includes all the Playwright tests

**Comment by tomcrane** [comment]
## Acceptance criteria

 - [ ] A new customer gets the correct DeliveryChannelPolicies and DefaultDeliveryChannels as defined #619

**Comment by donaldgray** [comment]
Entrypoint in current implementation where `DLCS:IngestDefaults` are read and used: https://github.com/dlcs/protagonist/blob/main/src/protagonist/API/Features/Image/Ingest/AssetProcessor.cs#L114

**Comment by JackLewis-digirati** [comment]
from meeting:

- settings only in engine
- api calls engine for setttings at the point it needs the settings
- as only engine, app settings is fine
