### ISSUE TITLE
Engine handles thumbs and iiif-img delivery channel

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#629]
Handle `thumbs` and `iiif-img` delivery-channels. Thumb handling using new service as per https://github.com/dlcs/protagonist/blob/develop/docs/adr/0006-engine-imageserver.md

Incoming asset may have one or the other or both, but a single "unit of work" needs to assess the asset and process in a certain order. See the ADR for sequence diagrams outlining flow.

Engine is always making SOME thumbs for an image, a union of the secret policy #627 and the supplied policy; the supplied policy may be nothing so it's a union of the secret policy and an empty set.

# Acceptance Criteria

- Playwright tests exist to describe all permutations in the ADR
- Engine produces the correct derivatives for each permutation, the broad categories are:
   - Thumbs only. Sizes are union of those specified in policy and "unofficial" sizes. (if `thumbs` channel only).
   - A JP2 and the unofficial thumbs (if `iiif-img` channel only).
   - A JP2 and union of specified + "unofficial" sizes (if `iiif-img` and `thumbs` channels).
- Thumbnail sizes are determined by looking at the actual size of the JPEG returned from Cantaloupe (currently these are provided in JSON payload returned from Appetiser).
- Update https://github.com/dlcs/protagonist/blob/develop/docs/storage-keys.md with location for transient origin-image once decided.

See below for possible permutations as channel, origin-strategy, image-policy and image format can affect processing. This is taken from the ADR - note that this isn't the purpose of that ADR and was working notes helped to produce output.

| d-c             | ImageOptPolicy | Origin Type  | Origin Format | What happens in Engine                                                                                                                              |
| --------------- | -------------- | ------------ | ------------- | --------------------------------------------------------------------------------------------------------------------------------------------------- |
| iiif-img,thumbs | default        | http*        | *             | Download origin. Calls Appetiser to convert. Uploads converted to S3. Calls Cantaloupe to generate thumbs. Uploads thumbs to S3.                    |
| iiif-img,thumbs | default        | http*        | image/jp2     | Download origin. Calls Appetiser to convert (would be a no-op). Uploads converted to S3. Calls Cantaloupe to generate thumbs. Uploads thumbs to S3. |
| iiif-img,thumbs | default        | s3-optimised | *             | Download origin. Calls Appetiser to convert. Uploads converted to S3. Calls Cantaloupe to generate thumbs. Uploads thumbs to S3.                    |
| iiif-img,thumbs | default        | s3-optimised | image/jp2     | Download origin. Uploads converted to S3. Calls Cantaloupe to generate thumbs. Uploads thumbs to S3.                                                            |
| iiif-img,thumbs | use-original   | http*        | *             | Download origin. Upload origin to S3. Calls Cantaloupe to generate thumbs. Uploads thumbs to S3.                                                    |
| iiif-img,thumbs | use-original   | s3-optimised | *             | Download origin. Call cantaloupe to generate thumbs (from origin). Upload thumbs to S3.                                                             |
| thumbs          | N/A            | http*        | *             | Download origin + upload to origin to S3 (_new location_). Call cantaloupe to generate thumbs. Upload thumbs to S3.                                 |
| thumbs          | N/A            | s3-optimised | *             | Call cantaloupe to generate thumbs from s3 origin. Upload thumbs to S3.                                                                             |
| file,thumbs     | N/A            | http*        | *             | Origin already at s3://dlcs-storage (from `file` worker). Call cantaloupe to generate thumbs. Upload thumbs to S3.                                  |
| file,thumbs     | N/A            | s3-optimised | *             | Call cantaloupe to generate thumbs from s3 origin. Upload thumbs to S3.                                                                             |

> * http* represents any non s3-optimised origin
> * Thumbnail sizes generated for `iiif-img,thumbs` are an exact union of specific policy sizes and #627 sizes
> * Delivery-channel of `iiif-img` only follows same rules as `iiif-img,thumbs` above, but thumbnail sizes are those from #627 setting
> * `thumbs` without `iiif-img` would need origin-image uploaded to an s3 DLCS-storage location but it only needs to be transient. Can store with a known prefix and use S3 lifecycle removes to cleanup.

**Comment by tomcrane** [comment]
This task is the Engine implementation.

**Comment by tomcrane** [comment]
This includes handling the single integer shorthand in #630

**Comment by JackLewis-digirati** [comment]
additionally, `HydrateAssetPolicies(asset);` in `EngineIngester` should be looked at as it currently fills out `imageOptimsationPolicies` and `thumbnailPolicies` for use in places such as appetiser, both of which are no longer needed by engine

**Comment by JackLewis-digirati** [comment]
default = `kdu_max`, use original = `use-original`

 just one worker to handle both image and thumbs - instead `AppetiserClient` could be split between thumbs and images

**Comment by JackLewis-digirati** [comment]
So I think there are 3 triggers for these actions:

- `SaveInDlcsStorage` - this is the "does everything" flag, and is generally the default - basically means the origin is stored in the DLCS and will be `false` when `use-original` image policy is explicitly set, and the origin is s3-optimised
- `IsTransient` - this is true when there is no image delivery channel, and the origin is s3 optimised (it's handled the same as if `SaveInDlcsStorage` is false).  It means that cantaloupe can use the origin directly
- `AlreadyUploaded` - this is true when the image has no delivery channel, but does have a  file and thumbs channel, meaning the image has already been uploaded to the DLCS, and does not require image processing to be completed

the order of evaluation of these triggers is as follows:

- `SaveInDlcsStorage` is `false`
- `IsTransient`
- `AlreadyUploaded` 
- `SaveInDlcsStorage`

This then translates into the below actions:

| d-c             | ImageOptPolicy | Origin Type  | Origin Format | What happens in Engine                                                                                                                        | trigger |
| --------------- | -------------- | ------------ | ------------- | --------------------------------------------------------------------------------------------------------------------------------------------------- |------------------------|
| iiif-img,thumbs | default        | http*        | *             | Download origin. Calls Appetiser to convert. Uploads converted to S3. Calls Cantaloupe to generate thumbs. Uploads thumbs to S3.                    | `SaveInDlcsStorage` |
| iiif-img,thumbs | default        | http*        | image/jp2     | Download origin. Calls Appetiser to convert (would be a no-op). Uploads converted to S3. Calls Cantaloupe to generate thumbs. Uploads thumbs to S3. | `SaveInDlcsStorage` |
| iiif-img,thumbs | default        | s3-optimised | *             | Download origin. Calls Appetiser to convert. Uploads converted to S3. Calls Cantaloupe to generate thumbs. Uploads thumbs to S3.                    | `SaveInDlcsStorage` |
| iiif-img,thumbs | default        | s3-optimised | image/jp2     | Download origin. Uploads converted to S3. Calls Cantaloupe to generate thumbs. Uploads thumbs to S3.                                                            | `SaveInDlcsStorage` |
| iiif-img,thumbs | use-original   | http*        | *             | Download origin. Upload origin to S3. Calls Cantaloupe to generate thumbs. Uploads thumbs to S3.                                                    | `SaveInDlcsStorage` |
| iiif-img,thumbs | use-original   | s3-optimised | *             | Download origin. Call cantaloupe to generate thumbs (from origin). Upload thumbs to S3.                                                             | `SaveInDlcsStorage` is `false` |
| thumbs          | N/A            | http*        | *             | Download origin + upload to origin to S3 (_new location_). Call cantaloupe to generate thumbs. Upload thumbs to S3.                                 | `SaveInDlcsStorage` |
| thumbs          | N/A            | s3-optimised | *             | Call cantaloupe to generate thumbs from s3 origin. Upload thumbs to S3.                                                                             | `IsTransient` |
| file,thumbs     | N/A            | http*        | *             | Origin already at s3://dlcs-storage (from `file` worker). Call cantaloupe to generate thumbs. Upload thumbs to S3.                                  | `AlreadyUploaded` |
| file,thumbs     | N/A            | s3-optimised | *             | Call cantaloupe to generate thumbs from s3 origin. Upload thumbs to S3.   | `IsTransient` |
