### ISSUE TITLE
Ensure s.json thumb sizes are emitted in `sizes` from named query manifests and single-asset manifests

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#631]
...so that clients can see what sized thumbs were created in bulk, for a named query, as well as individually.

Clients including the DDS.

At the moment protagonist deduces these sizes, so is potentially prone to rounding errors.
It won't be doing any deducing in future, just reading the sizes that cantaloupe made.

Requirement outlined above resulted in RFC being written (#767)

## Update after RFC

RFC documents how metadata that can be read in bulk will be stored in `AssetApplicationMetadata`.

This ticket is blocked by #787 - once that is done we will have the `AssetApplicationMetadata` table available. This ticket is then to update classes involved in NQ + single-asset manifest generation (likely `IIIFManifestBuilder` and/or `IIIFCanvasFactory`) to read the thumbnail sizes generated, rather than deducing them.

However, when first introduced, and possibly for some time after, this new table won't be populated with `"ThumbSizes"` metadata value for _every_ asset. So until that happens we need a method of attempting to read the actual values but falling back to calculating if there is no `"ThumbSizes"` metadata.

Initially upon release all new-format (ie using IIIF Size Param) thumb sizes will be based on confined sizes (`!w,h`) so we will be able to calculate them using existing methods in `AssetX` (updating method to only calculate confined thumb sizes). 

Implementation points:
* We don't want to `.Include()` in the base NQ IQueryable generator - need a hook to include relevant data only depending on projection.
* It doesn't feel correct for Orchestrator to load assets with PolicyData. It will load `ImageDeliveryChannel` with PolicyId - this can be used to load + cache PolicyData if required (use same local caching mechanism as is currently happening with ThumbsPolicy).
* As well as `"sizes` the sizes read here need to populate the `"thumbnail"` property on manifest

### Acceptance Criteria

* Named query and single-item manifests output sizes property read from database
* Where no thumbs sizes found in database calculate from image dimensions + policyData
* Logic to fallback to calculating should be controllable by a config flag - this should be a date to control fallback based on last image ingest date.

**Comment by donaldgray** [comment]
`IIIFManifestBuilder` is central class used for generating both NQ + single-asset manifests.

**Comment by tomcrane** [comment]
`GetThumbnailSizesForImage` should read S3 sizes.json.

**Comment by donaldgray** [comment]
https://github.com/dlcs/protagonist/blob/52a9f751d7202b64554cfbc8b5ff47f5ca226b67/src/protagonist/Orchestrator/Infrastructure/IIIF/IIIFCanvasFactory.cs#L186 is the method call to work out sizes per canvas (ie image).

We will need to take performance implications into account, particularly for larger NQs

**Comment by tomcrane** [comment]
Also need to make sure that "secret" thumbnails are also present in the sizes list.

**Comment by JackLewis-digirati** [comment]
This ticket will also need to cover handling skipped tests in `NamedQueryTests` and additional tests in `ManifestTests` to cover the retrieval of thumbnail sizes from the database (as opposed to s.json that it uses before this ticket)
