### ISSUE TITLE
API endpoints to manage default delivery channels and delivery channel policies

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#634]
- Allow a customer to create new default delivery channels on Customer and Space
- Allow a customer to edit and delete default delivery channels
- Allow a customer to view all [deliveryChannelPolicies ](https://deploy-preview-2--dlcs-docs.netlify.app/api-doc/customer#deliverychannelpolicies) (via child collections
- Allow a customer to add new ones and edit existing ones
- AV policy data is from a hard-coded list of string presets that map to settings via #709

**Comment by tomcrane** [comment]
TODO - split this ticket

Some further observations (incomplete list)

 - You can't delete a policy that's in use
- If you edit a policy (eg change policyData) no reprocessing happens automatically
- You can't change the channel of a policy
- `policyData` is validated as correct for the channel:
   - `thumbs` is an array of valid IIIF `size` params (we have this code already) 
   - `iiif-img` is either "default" or "use-original"
   - `iiif-av` is one of the known list of presets (audio-aac-128 etc)
   - `file is` "none"

(need to split this issue as iiif-av values are a dependency)

**Comment by donaldgray** [comment]
Ticket split and following tickets created:
* https://github.com/dlcs/protagonist/issues/719
* https://github.com/dlcs/protagonist/issues/720
* https://github.com/dlcs/protagonist/issues/721

**Comment by tomcrane** [comment]
Close as split as above
