### ISSUE TITLE
Unable to delete assets that failed to ingest

### ISSUE THREAD

**Issue by griffri** [dlcs/protagonist#636]
The API currently returns `404 Not Found` if you attempt to delete an asset that cannot be ingested (i.e, the file type is unrecognized) but it should be deletable regardless of the state it's in.

**Comment by JackLewis-digirati** [comment]
NOTE: this needs to be checked with `File` assets as well

**Comment by donaldgray** [comment]
Under Deliverator there are instances where `ImageLocation` records could be deleted. If the root cause of this issue is caused by missing `ImageLocation` then it could prevent items that were ingested via Deliverator being deleted
