### ISSUE TITLE
Optimised origin - more options needed

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#64]
Current DLCS has the notion of an optimised origin. This is typically an S3 bucket that it has permissions to access, but is not its own bucket. 

However, it conflates two things:

optimised origin = they are tile-ready JP2s
optimised origin = don't copy source image to DLCS, treat as own storage

They should be independent!

 - a customer bucket might contain JPEGs and tiffs
 - images might already be tile-ready JP2s, but they are in GitHub, or an FTP server etc.

**Comment by tomcrane** [comment]
We need two different terms for:

1. origins that can be relied on to contain tile-ready JP2s
2. origins that DLCS can treat as its own storage

...so that we can clearly differentiate between these two ideas both in the UI of the DLCS portal and in the DLCS' behaviour.

**Comment by tomcrane** [comment]
Wellcome bron digital will be affected by this - non-JP2 images for DLCS, but they are from the "optimised" storage bucket.

**Comment by tomcrane** [comment]
> origins that can be relied on to contain tile-ready JP2s

Is this even a concept for the DLCS? Or is it a flag supplied on the ingest request?
So DDS, when processing digitised JP2s, always sets this flag.
DDS when processing random folders of born digital images, does not set this flag and leaves it up to the DLCS.

Also DLCS might choose not to transcode. If the image is a 800x500 jpg, is it worth creating a JP2? Or just have cantaloupe surface an image service directly from that image?

**Comment by donaldgray** [comment]
I think it could be useful to have a priority associated with a customerOriginStrategy. Currently the customerOriginStrategies are iterated through until a match is found - first match wins. However, there's no order to the items - they're read in db order.

This would make it easier to handle scenarios where you have 2 customerOriginStrategies - e.g. 1 capturing everything in a bucket and the other a subset of those. Currently we'd need to have the "capture everything" regex exclude the subset to ensure it's used.

**Comment by donaldgray** [comment]
#393 and #384 will alter how "file" delivery-channel is handled. 

Assets with delivery-channel of 'file' are copied to DLCS storage buckets and served from there. The cos is used to determine logic for copying to output bucket. However, we may want to _not_ copy optimised-origins and serve directly from origin in orchestrator.

**Comment by donaldgray** [comment]
Note - PR #447 added ADR related to this ticket
