### ISSUE TITLE
priority queue requires a family or delivery channel to be set

### ISSUE THREAD

**Issue by JackLewis-digirati** [dlcs/protagonist#657]
While writing tests for the priority queue, the following response was observed:

```
{
    "@type": "Error",
    "statusCode": 400,
    "status": 400,
    "title": "Create priority batch failed: Validation failed",
    "detail": "Priority queue only supports image assets",
    "instance": "https://api.dlcs-stage.digirati.io",
    "description": "Priority queue only supports image assets"
}
```

After checking all assets in the payloads, it appears as if the payload requires either a image family or a delivery channel to be set to be handled as an image.  This differs from other calls such as the normal batch call to work.

The code that breaks is likely due to these lines being called before defaulting the value in `CreateBatchOfImages.cs`:

```
if (request.Assets.Any(a =>
                    a.Family != AssetFamily.Image && !a.HasDeliveryChannel(AssetDeliveryChannels.Image)))
            {
                return ModifyEntityResult<Batch>.Failure("Priority queue only supports image assets",
                    WriteResult.FailedValidation);
            }
```

**Comment by tomcrane** [comment]
Make sure the batch is rejected before Engine does any processing of any of the images.

**Comment by JackLewis-digirati** [comment]
This also will need to update the automated test payloads to remove `family` from `t0003.json`
