### ISSUE TITLE
Modify CleanupHandler CDN invalidation

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#664]
The `deleteImages` endpoint can take batch of images to delete. It will remove them from the database and then raise an asset-modified notification to delete the rest of the images.

The logic to send invalidations to CloudFront can very quickly hit the maximum allowed as we use wildcards for paths, which results in `TooManyInvalidationsInProgressException` being thrown by AWS SDK.

Do we want to _always_ invalidate from CF? If so we'll need to handle them better, e.g. Retry? Use full paths rather than wildcards (maybe a known set of image requests for info.json, thumb sizes, all known av derivatives etc).
OR do we somehow allow deletions to be marked as `requiresCDNInvalidation`. If so, we still may need better handling to deal with any failures.

This may be a non-issue in the future but the CleanupHandler uses DeliveryChannel to work out which `/iiif-img/`, `/thumbs/`, `/iiif-av/`, `/file/` paths need invalidating but also uses `AssetFamily` to work out if `iiif-manifest` needs invalidation. These should be aligned to use deliveryChannel, falling back to AssetFamily if DC is empty.

**Comment by tomcrane** [comment]
#676 reduces the amount of cloudfront invalidations but we still have the limiting problem.

If the invalidation fails, the message is re-queued; SQS will try 10 times before putting on the dead letter queue. But we may well hit 10 fails if you delete lots of things concurrently. So we need to 

Can we query cloudfront to see if invalidations are in flight, so we can hold off until they clear?

Cleanup handler a separate lambda that picks up - but can time out and die.

Refinement conclusion:

don't do this. #676 eases the problem. We will still attempt cloudfront if asked for, but it may fail. In which case - phone us.

Later we can write a tool to do bulk invalidation in emergencies.
