### ISSUE TITLE
Cleanup Handler use of Delivery Channels

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#691]
This may be a non-issue in the future but the CleanupHandler uses DeliveryChannel to work out which `/iiif-img/`, `/thumbs/`, `/iiif-av/`, `/file/` paths need invalidating but also uses AssetFamily to work out if iiif-manifest needs invalidation. These should be aligned to use deliveryChannel, falling back to AssetFamily if DC is empty.

## Acceptance Criteria

* CleanupHandler uses values from `ImageDeliveryChannels` table rather than `Asset.DeliveryChannels` to work out what needs deleted.
* CleanupHandler doesn't use AssetFamily to drive any decisions on what is to be deleted.

**Comment by donaldgray** [comment]
Relevant code:
Using delivery-channel: https://github.com/dlcs/protagonist/blob/main/src/protagonist/CleanupHandler/AssetDeletedHandler.cs#L110 
Using DC: https://github.com/dlcs/protagonist/blob/main/src/protagonist/CleanupHandler/AssetDeletedHandler.cs#L129
