### ISSUE TITLE
Include all custom fields in single issue manifest and named queries

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#698]
This is a part of issue #488 - split out because this is easy to implement immediately.

string1, string2, number1, number2, etc, as well as tags and roles, should be emitted as IIIF `metadata` label value pairs on each `Canvas`.

**Comment by donaldgray** [comment]
Both the single-item (`/iiif-manifest/*`) and named-query (`/iiif-resource/*`) manifests use the same class for constructing Canvases, the `IIIFCanvasFactory` - https://github.com/dlcs/protagonist/blob/main/src/protagonist/Orchestrator/Infrastructure/IIIF/IIIFCanvasFactory.cs

There are 2 different methods corresponding to the 2 different supported IIIF ImageApi versions (although these appear similar they are different strongly typed classes that share very little hence the need for separate methods):
* `CreateV3Canvases`
* `CreateV2Canvases`

Each of these methods takes a `List<Asset>` - this will be a single asset for single-item manifests and 1+ for named-query manifests. The logic for getting the matching assets is already working so all that will need to be added is `metadata` to the `IIIF2.Canvas` and `IIIF3.Canvas` objects.
