### ISSUE TITLE
Write Playwright tests for Delivery Channel API documentation

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#703]
These tests will all fail at first obviously and should be marked as expected to fail.

They test the proposed API interactions in the new API docs.

Writing the tests will help uncover any issues in the design. This is similar in intent to https://github.com/dlcs/protagonist/issues/617, but that task on its own is not sufficient, and is not part of the DLCS codebase.

**Comment by tomcrane** [comment]
new [API Docs](https://deploy-preview-2--dlcs-docs.netlify.app/api-doc/delivery-channels)

**Comment by tomcrane** [comment]
Acceptance Criteria

These tests will evolve as the work progresses but there are some obvious steps

1. An initial set of NAMED (but empty) test methods. We can review these and agree that they are actually going to be testing the proposed API
2. The tests are marked as expected to fail so as not to interfere with regular tests
3. Implemented bodies for those initial test methods, verifying that delivery channels and policies can be created at different levels, that assets are granted "inherited" channels, that assets return channels correctly etc - these acceptance criteria won't spell this out in full as that is the task here.
4. Further test methods as the implementation evolves

**Comment by griffri** [comment]
- We need to check the behaviours of assets with different delivery channels
- The effects of different thumbnail policies should be tested - could grab the thumbnail sizes from Orchestrator
These will likely need to be split into different files.
