### ISSUE TITLE
API endpoints to manage delivery channel policies

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#719]
Allow a customer to manage their own delivery channel policies.

Dependant by https://github.com/dlcs/protagonist/issues/709

See https://deploy-preview-2--dlcs-docs.netlify.app/api-doc/delivery-channels#preset-policies for related documentation.

## Acceptance Criteria

Support the following verbs:

* `GET /customers/{customer}/deliveryChannelPolicies/{channel}/{name}` - retrieve policy
  * Returns `vocab:DeliveryChannelPolicy`
  * Returns 200 if found.
* `PUT /customers/{customer}/deliveryChannelPolicies/{channel}/{name}` - Create or update policy
  * Returns created/updated `vocab:DeliveryChannelPolicy`
  * Returns 201 if created, 200 if updated.
  * `name` is not permitted required/ignored. 
  * `displayName` is optional.
  * `channel` is required and must be one of known list: `iiif-img`, `iiif-av`, `thumbs` (this comes from URL)
    * Cannot create a `file` policy as there is no available policyData customisations for this.
    * Cannot create a `iiif-img` policy as there is no available policyData customisations for this.
  * `policyData` has different validation rules depending on channel:
    * `thumbs` is an array of valid IIIF size params ([`SizeParameter.Parse()`](https://github.com/digirati-co-uk/iiif-net/blob/main/src/IIIF/IIIF/ImageApi/SizeParameter.cs#L47) can be used, may need modifications)
    * ~`iiif-img` is either "default" or "use-original"~
    * `iiif-av` is one of the known list of presets (as defined in #709)
  * Asset is not reprocessed when policy changed
* `POST /customers/{customer}/deliveryChannelPolicies/{channel}` - Create policy (via parent collection)
  * Returns 201 Created on success
  * `name` is required as not on path. Validate `name` is not already used. Returns 409 Conflict if `name` in use.
  * Validation rules apply as per `PUT`, above
* `PATCH /customers/{customer}/deliveryChannelPolicies/{channel}/{name}`
  * Returns updated `vocab:DeliveryChannelPolicy`
  * Returns 200 if updated
  * `name` or `channel` cannot be edited
  * Validation rules apply as per `PUT`, above
  * Asset is not reprocessed when policy changed
* `DELETE /customers/{customer}/deliveryChannelPolicies/{channel}/{name}`
  * Returns 204 NoContent if deleted
  * Cannot delete a policy that is in use. Returns 409 Conflict/400 BadRequest
* `GET /customers/{customer}/deliveryChannelPolicies` - retrieve available collections of policies per channel
  * Returns 200 
  * Returns `hydra:Collection` of `hydra:Collection`
* There are Playwright tests for all the above

> Returned status codes not exhaustive. Standard rules apply for NotFound, BadRequest, InternalServerError etc

**Comment by griffri** [comment]
The following route will also need to be implemented:

- GET /customers/{customer}/deliveryChannelPolicies/{channel}
  - Returns 200
  - Returns `hydra:Collection` of `vocab:DeliveryChannelPolicy`
