### ISSUE TITLE
Thumbnail service for AV content, PDFs and more

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#73]
A thumbnail service should be provided for anything that could have a visual thumbnail - video, PDFs and more.

This will be much easier to do if Cantaloupe is the backing image server.

**Comment by donaldgray** [comment]
Related to #249

**Comment by tomcrane** [comment]
click on "Football films"

https://samvera-labs.github.io/bloom-iiif/

```
{
"thumbnail": [
    {
      "id": "https://example.org/img/thumb.jpg",
      "type": "Image",
      "format": "image/jpeg",
      "width": 300,
      "height": 200
    },
    {
      "id": "https://example.org/video/video.mp4?t=60,75",
      "type": "Video",
      "format": "video/mp4",
      "width": 300,
      "height": 200,
      "duration": 15
    }
  ]
}
```

You need two pieces of info:
1) time for the image thumbnail - e.g., 34.44
2) range for the video thumbnail - e.g., 12.8 - 31.3
...and then the DLCS can put the IIIF together

Cantaloupe can supply the image thumb from the timecode - can even supply an image service for that frame

These are just two extra DB columns on video type assets.

**Comment by tomcrane** [comment]
This information also appears on the single asset manifest #488

**Comment by tomcrane** [comment]
For Wellcome born digital work we introduced the concept of delivery channel - a flexible way of specifying what transformations (if any) should be applied to an asset. An asset (such as an image or a PDF) may have multiple delivery channels. A JPEG2000 could have the `iiif-img` delivery channel _and_ the `thumbs` delivery channel _and_ the `file` delivery channel, meaning "make a level-2 IIIF Image Service available", "make preset thumbs available as a level-0 image service", "serve the original image file as-is". 

## Suggested approach

* The `thumbs` delivery channel is ALWAYS serviced by the same application - [Thumbs](https://github.com/dlcs/protagonist/tree/main/src/protagonist/Thumbs). And more generally, the routing is simple - one application per delivery channel.
* The `thumbs` delivery channel, and therefore [Thumbs](https://github.com/dlcs/protagonist/tree/main/src/protagonist/Thumbs), always serves jpeg images no matter what the asset is. It exposes a level-0 IIIF Image service with `sizes` only. If we want moving-picture thumbs as mp4s or audio-clip thumbs, that's a new delivery channel, called something else. `clips` for example.
* They are never access controlled, so thumbs don't get made for access controlled assets.
* The point is speed, so Engine always makes the configured sizes at ingest-time. Engine can make thumbs for any asset as long as it knows how to.

This means the *policy* for the thumbs channel is always the [same syntax](https://github.com/dlcs/protagonist/issues/66#issuecomment-1609800287) - e.g., `["!1024,1024", "880,"]` because it's always making the same kind of thing. We might have a couple of extensions to that syntax to additionally specify a page index if the asset is a pdf, or a `t` time point if it's a video. (does that mean you can supply a one-off customised policy for an asset as well as a precanned policy id?)

So the Thumbs application never knows about Cantaloupe. It's not making decisions based on the asset content type and serving a jpeg, or proxying to SpecialServer, or doing something else.

We might have more complex dynamic image service generation for AV per frame taking advantage of live-proxying to cantaloupe, but that's a different delivery channel that we could investigate later.

Thumbs always serves a level-0 IIIF Image Service. Engine makes the thumbs using Special Server for images, pdfs and videos. Engine could make thumbs for other types of asset differently in future but Thumbs doesn't know or care. The API caller - who registers the asset - doesn't need to instruct Engine with a policy-per-content-type.

What does engine or API do if the caller asked for the `thumbs` channel for an asset that we can't make thumbs for? E.g., a spreadsheet? Do we just accept it but Engine will skip over it and therefore the /thumbs/ app will return 404 for the info.json? We may be capable of providing thumbs for a particular format later, so the caller could register it in hope and anticipation.

Future delivery channels could be things like:

 - `clips` for video snippets
 - `iiif-img-from-video` for arbitrary level 2 image services from arbitrary time points
 - `av-derivatives` for dynamic creation of new derivatives (give me this video from 10s to 30s at 720p as an avi) - ffmpeg-as-a-service
 - `iiif-img-from-pdf` for arbitrary level 2 image services from arbitrary pdf pages

... as well as adding more supported content types to existing channels.

In theory the two `iiif-img-*` above could just be the `iiif-img` channel but they both need extra parameters and really the `iiif-img` channel should be reserved for images only.

**Comment by tomcrane** [comment]
This needs re-stating after we have all decided on the API approach. See prototype Delivery Channels documentation.

**Comment by tomcrane** [comment]
Closing this as it has now become ADRs 0006 and 0007.
