### ISSUE TITLE
Engine handles File delivery channel

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#747]
Validate that current File handling (`FileChannelWorker`) continues to work correctly.

## Acceptance Criteria

* File channel handling still works as-is

**Comment by griffri** [comment]
Checklist:
- [ ] An asset using the `file` channel can be created
- [ ] The file is stored on S3
- [ ] The file can be retrieved via the API
- [ ] Setting the delivery channels to `none` removes access to this file
