### ISSUE TITLE
Remove LegacyIngestEvent and InitialOrigin functionality

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#759]
The following functionality is no longer required and can be removed:

* `LegacyIngestEvent` and all usages. This was used for testing Deliverator-API -> Protagonist-Engine interactions to validate old/new behaviour. At one point there was a possibility of rolling out Protagoinst-Engine while still using Deliverator-API but this won't happen now. `UseLegacyEngineMessage` appSetting controls whether API uses this format so can also be removed.
* `"InitialOrigin"` usage in Portal. This field was removed in #622/#750 but is still available in CSV upload.

**Comment by griffri** [comment]
When removing `LegacyIngestEvent`, it might be a good idea for us also change `IngestAssetRequest` as legacy support is currently the only reason why it contains a full asset rather than just an AssetId.

**Comment by donaldgray** [comment]
> When removing LegacyIngestEvent support, should IngestAssetRequest also be changed so that it only contains a AssetId?
The full asset is currently only used for the legacy Engine.

This was fixed in #763
