### ISSUE TITLE
Populate missing deliveryChannel payloads in API results

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#796]
This ticket covers 2 related issues - populating of `"deliveryChannels"` and `"wcDeliveryChannels"` properties on Hydra Image API payloads.

## "deliveryChannels"
`"deliveryChannels"` field is not populated in some Hydra Image payloads, it's returning an empty array only. This is happening for (check all other payloads that can return Image, either in bulk or individually). Each entry here should be returning the fully populated `"deliveryChannels"` property.
:
* POST `/customers/{customerId}/allImages`
* GET `/customers/{customerId}/queue/batches/{batchId}/images`
* GET `/customers/{customerId}/spaces/{spaceId}/images`
* PATCH `/customers/{customerId}/spaces/{spaceId}/images`
* PATCH `/customers/{customerId}/spaces/{spaceId}/images/{imagesId}`

## "wcDeliveryChannels"

`"wcDeliveryChannels"` is always returned as an empty array. This should returned the channels as an array of strings (ie the old style delivery-channel format). E.g. `"wcDeliveryChannels": ["iiif-img", "thumbs"]`. This needs to happen in all places where a Hydra image is returned

**Comment by griffri** [comment]
Regarding the PATCH endpoints:
Patching an asset currently wipes any delivery channels associated with it, if none are specified in the JSON payload. This is a bug and it will need to be fixed to ensure that the correct `deliveryChannels` are returned in the response JSON.
