### ISSUE TITLE
Delivery channel pre-release checklist 

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#799]
This ticket will capture a list of any pre release checks/actions that need to happen prior to creating DeliveryChannels release

* [ ] - Validate ThumbnailPolicy is not used in any code execution paths (models can still exist until #623 done)
* [ ] - Validate ImageOptimisationPolicy is not used in any code execution paths (models can still exist until #623 done)

**Comment by JackLewis-digirati** [comment]
`ImageOptimisationPolicy` is used in a few places outside of the various policy controllers:

- `AssetConverter`
  - Used to return the converted hydra policy (but it does a null check, so images without the value will just not return it
- `ImageController`
  - This useage is specific to legacy ingest, and all it's doing is returning 400 if the exist, so shouldn't be broken
- `HydraImageValidator`
  - it's used in `WcDeliveryChannels` validation to check if the policy is valid for the `WcDeliveryChannel`

**Comment by JackLewis-digirati** [comment]
`ThumbnailPolicy` is used in the following places:

- `AssetPreparer`
  - if the policy differs netween old and new, it sets `requireReingest`
- `AssetConverter`
  - used in the same way as `ImageOptimisationPolicy` - will be returned to front end if set
- `DlcsContext`
  - it's a required property on the DB, but also gets a default value of `original`
