### ISSUE TITLE
Tiles cached if source cannot be found?

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#885]
Reported by Wellcome (so, at time of reporting, Cantaloupe 5.0.5, kdu 8.4.1).

The lustre volume for Cantaloupe was reaching capacity so some jp2's couldn't be orchestrated. This resulted in 404's being returned from Cantaloupe. After disk space was cleared up the issue went away, however user is still seeing blurry tiles cached in browser. Switching to an anonymous browser resolved issue so it looks like issue was browser related.

Check:
* Are cache headers set for these 404 responses? If so, from where? Are they private or public?
* Are they cached anywhere else?

**Comment by griffri** [comment]
I removed a newly orchestrated image from an Orchestrator volume and attempted to retrieve a tile in an anonymous browser - this resulted in a 404 with `Cache-Control: public...` and `X-Cache: HIT` headers set.

> Are they cached anywhere else?
Currently looking into this.
