### ISSUE TITLE
Batch completed callback notification

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#922]
On batch completion we need to raise an SNS notification.

JSON payload should include:
* CustomerId (also include as a Attribute)
* BatchId
* Counts (success / fail / error)
* Started and Finished count

Acceptance criteria
* Notification raised when entire batch completes 'normally' whether success or failure
* Notification raised when batch completes via "test for superseded"

**Comment by griffri** [comment]
Tested - moving to 'done'.
